In the case where the convert.WebMacro program is run on a directory, Ant's DirectoryScanner is used to grab a list of WM files to convert. A NoClassDefFoundError was being thrown because Ant was never in the classpath supplied to the JVM (and we are building the classpath from scratch, user classpath be damned!).  We now use the Ant JAR from our build/lib/ directory.
git-svn-id: https://svn.apache.org/repos/asf/jakarta/velocity/trunk@74926 13f79535-47bb-0310-9956-ffa450edef68